### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [Mikescher/youtube-dl-viewer#2]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the [AGPL-3.0-or-later license](https://www.gnu.org/licenses/agpl-3.0.html) so that others are encouraged to contribute changes back to your project.  Unlicense would also make sense to match [youtube-dl's license](https://github.com/ytdl-org/youtube-dl/blob/master/LICENSE), but AGPL works better for web pages.

**Comment by Mikescher** [comment]
A thanks, I totally forgot to add one
